spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_delivery
    username: root
    password: leonel
    driver-class-name: com.mysql.cj.jdbc.Driver
    server:
      port: 8080


  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
    #ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect